### ISSUE TITLE
Performance

### ISSUE THREAD

**Issue by codingluke** [metavida/remote_ip_proxy_scrubber#2]
Hi, I'm interessted using you gem, I have just one big question mark, performance, what would you say, can it be used on an app with approx 300 parallel users?

**Comment by metavida** [comment]
Hi @codingluke, I haven't done any formal performance metrics on the middle-ware & can't offer you any guarantees, but we've started using this middleware in production across several of our apps. Cherry-picking one example, we've got a Rails app handling an average of 600 requests per minute that's continuing to perform quite nicely with X-Forwarded-For IP filtering in place. I'd love to hear whether or not it works for you or if you run into any glitches!
