### ISSUE TITLE
IPv4 vs IPv6

### ISSUE THREAD

**Issue by jobinthepast** [metavida/remote_ip_proxy_scrubber#4]
Thank you for creating a great gem. It works out of the box. However I got some IPv6 values on registrations#new action, something like `2a02:1205:34e8:d50:1db1:1d9c:699f:4869` or `2a02:1205:5071:94d0:e950:2e3:db19:ac9e` while most of the other are IPv4.

Do you have any idea why this happen?

**Comment by metavida** [comment]
That looks like legitimate traffic from customers of yours who are using IPv6. I checked [Cloudflare's current list of IPv6 ranges](https://www.cloudflare.com/ips/) and confirmed that the `2a02:1205::/32` range is *not* owned by Cloudflare. 

Were you **not** expecting IPv6 traffic, based on your Cloudflare config?

**Comment by metavida** [comment]
@giangnguyennet since I haven't heard back from you & as best I can tell it seems like this is not a bug, I'm marking this issue as closed. Feel free to re-open if you have more details or questions.
